### ISSUE TITLE
HTML Ontwerp

### ISSUE THREAD

**Issue by DivaniNL** [DivaniNL/your-tribe-profile-card#2]
![IMG_3625](https://github.com/user-attachments/assets/f98dd04e-a8db-4c0d-8d94-9aa3a068ce76)

**Comment by KoopReynders** [comment]
Schetstechnieken: 
Maak een wireframe met zwarte pen. Het is beter als je met een fineliner schrijft en niet met een stof, dat is beter leesbaar. . Probeer je schetsen wat netter te maken zodat anderen beter zien wat de bedoeling is. 
Schets in de wireframe alle content. Zo nodig met een 'scribble'.  Probeer iets meer content in de schets te schrijven. 

De code lijkt prime. Gebruik MDN HTML reference als bron om te lezen welke elementen je waar voor gebruikt.
